title: NatureQ Blog
description: 自然卷
baseurl: ""
url: "https://doyounatureq.github.io"
theme: minima
author:
  name: NatureQ
  email: doyougame@qq.com

markdown: kramdown
highlighter: rouge
future: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num"

social_links:
  github: https://github.com/DoYouNatureQ
  bilibili: https://space.bilibili.com/361090625
  email: mailto:doyougame@qq.com
