title: NatureQ's Blog
description: 技术与幻想并行的自留地
baseurl: ""
url: "https://natureq.top/"
theme: minima
author:
  name: NatureQ
  email: doyougame@qq.com

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page:num"

social_links:
  github: https://github.com/doyounatureq
  twitter/x: https://x.com/doyounatureq
  email: doyougame@qq.com
