title: NatureQ's Blog
description: 技术与幻想并行的自留地
baseurl: ""
url: "https://yourusername.github.io"
theme: minima
author:
  name: NatureQ
  email: your@email.com

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num"

social_links:
  github: https://github.com/yourusername
  twitter: https://twitter.com/yourname
  email: mailto:your@email.com
